# from PyQt6.QtCore import Qt
# from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Basketball(object):
    def setupUi(self, Basketball):
        Basketball.setObjectName("Basketball")
        Basketball.resize(1024, 682)
        Basketball.setStyleSheet("")
        self.stackedWidget = QtWidgets.QStackedWidget(Basketball)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setStyleSheet("")
        self.page1.setObjectName("page1")
        self.Background1 = QtWidgets.QLabel(self.page1)
        self.Background1.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.Background1.setStyleSheet("background-image: url(C:/Users/HP/Desktop/things/offterm/court/basketball/background2.png);")
        self.Background1.setText("")
        self.Background1.setObjectName("Background1")
        self.ProjectName = QtWidgets.QLabel(self.page1)
        self.ProjectName.setGeometry(QtCore.QRect(237, 110, 550, 140))
        self.ProjectName.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 65pt \"Bauhaus 93\";")
        self.ProjectName.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.ProjectName.setObjectName("ProjectName")
        self.AnalyseMode = QtWidgets.QPushButton(self.page1)
        self.AnalyseMode.setGeometry(QtCore.QRect(370, 270, 100, 40))
        self.AnalyseMode.setStyleSheet("background-color: rgb(120, 170, 195);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Bauhaus 93\";")
        self.AnalyseMode.setObjectName("AnalyseMode")
        self.TrainMode = QtWidgets.QPushButton(self.page1)
        self.TrainMode.setGeometry(QtCore.QRect(540, 270, 100, 40))
        self.TrainMode.setStyleSheet("background-color: rgb(120, 170, 195);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Bauhaus 93\";")
        self.TrainMode.setObjectName("TrainMode")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.AnalyseVideo = QtWidgets.QLabel(self.page2)
        self.AnalyseVideo.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.AnalyseVideo.setObjectName("AnalyseVideo")
        self.court = QtWidgets.QLabel(self.page2)
        self.court.setGeometry(QtCore.QRect(912, 45, 112, 120))
        self.court.setObjectName("court")
        self.Back1 = QtWidgets.QPushButton(self.page2)
        self.Back1.setGeometry(QtCore.QRect(930, 640, 81, 26))
        self.Back1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"font: 15pt \"Bauhaus 93\";")
        self.Back1.setObjectName("File")
        self.Stop = QtWidgets.QPushButton(self.page2)
        self.Stop.setGeometry(QtCore.QRect(830, 640, 81, 26))
        self.Stop.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"font: 15pt \"Bauhaus 93\";")
        self.Stop.setObjectName("Stop")
        self.Hit = QtWidgets.QLabel(self.page2)
        self.Hit.setGeometry(QtCore.QRect(312, 570, 400, 70))
        self.Hit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 48pt \"Bauhaus 93\";")
        self.Hit.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Hit.setObjectName("Hit")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.shootbackground = QtWidgets.QLabel(self.page3)
        self.shootbackground.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.shootbackground.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.shootbackground.setObjectName("shootbackground")
        self.shoot = QtWidgets.QLabel(self.page3)
        self.shoot.setGeometry(QtCore.QRect(10, 91, 346, 500))
        self.shoot.setStyleSheet("background-image: url(C:/Users/HP/Desktop/things/offterm/court/ba/shootbackground.png);")
        self.shoot.setObjectName("shoot")
        
        self.court2 = QtWidgets.QLabel(self.page3)
        self.court2.setGeometry(QtCore.QRect(0, 91, 346, 500))
        self.court2.setObjectName("court2")

        self.Total1 = QtWidgets.QLabel(self.page3)
        self.Total1.setGeometry(QtCore.QRect(443, 240, 220, 60))
        self.Total1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Total1.setObjectName("Total1")
        self.Hit2 = QtWidgets.QLabel(self.page3)
        self.Hit2.setGeometry(QtCore.QRect(662, 170, 220, 60))
        self.Hit2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Hit2.setObjectName("Hit2")
        self.Back2 = QtWidgets.QPushButton(self.page3)
        self.Back2.setGeometry(QtCore.QRect(930, 640, 81, 26))
        self.Back2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"font: 15pt \"Bauhaus 93\";")
        self.Back2.setObjectName("Back2")
        self.Background3 = QtWidgets.QLabel(self.page3)
        self.Background3.setGeometry(QtCore.QRect(430, 146, 464, 390))
        self.Background3.setStyleSheet("background-color: rgba(0, 0, 0, 65);")
        self.Background3.setText("")
        self.Background3.setObjectName("Background3")
        self.Hit1 = QtWidgets.QLabel(self.page3)
        self.Hit1.setGeometry(QtCore.QRect(443, 170, 220, 60))
        self.Hit1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Hit1.setObjectName("Hit1")
        self.Rate1 = QtWidgets.QLabel(self.page3)
        self.Rate1.setGeometry(QtCore.QRect(443, 310, 220, 60))
        self.Rate1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Rate1.setObjectName("Rate1")
        self.Speed1 = QtWidgets.QLabel(self.page3)
        self.Speed1.setGeometry(QtCore.QRect(443, 380, 220, 60))
        self.Speed1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Speed1.setObjectName("Speed1")
        self.Angle1 = QtWidgets.QLabel(self.page3)
        self.Angle1.setGeometry(QtCore.QRect(443, 450, 220, 71))
        self.Angle1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Angle1.setObjectName("Angle1")
        self.Total2 = QtWidgets.QLabel(self.page3)
        self.Total2.setGeometry(QtCore.QRect(662, 240, 220, 60))
        self.Total2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Total2.setObjectName("Total2")
        self.Rate2 = QtWidgets.QLabel(self.page3)
        self.Rate2.setGeometry(QtCore.QRect(662, 310, 220, 60))
        self.Rate2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Rate2.setObjectName("Rate2")
        self.Speed2 = QtWidgets.QLabel(self.page3)
        self.Speed2.setGeometry(QtCore.QRect(662, 380, 220, 60))
        self.Speed2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Speed2.setObjectName("Speed2")
        self.Angle2 = QtWidgets.QLabel(self.page3)
        self.Angle2.setGeometry(QtCore.QRect(662, 450, 220, 60))
        self.Angle2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bauhaus 93\";")
        self.Angle2.setObjectName("Angle2")
        self.Background3.raise_()
        self.Total1.raise_()
        self.Hit2.raise_()
        self.Back2.raise_()
        self.Hit1.raise_()
        self.Rate1.raise_()
        self.Speed1.raise_()
        self.Angle1.raise_()
        self.Total2.raise_()
        self.Rate2.raise_()
        self.Speed2.raise_()
        self.Angle2.raise_()
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.Background4 = QtWidgets.QLabel(self.page4)
        self.Background4.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.Background4.setStyleSheet("background-image: url(C:/Users/HP/Desktop/things/offterm/court/basketball/background3.png);")
        self.Background4.setText("")
        self.Background4.setObjectName("Background4")
        self.BasketballMode = QtWidgets.QPushButton(self.page4)
        self.BasketballMode.setGeometry(QtCore.QRect(0, 261, 220, 160))
        self.BasketballMode.setStyleSheet("background-color: rgb(255, 184, 2);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Bauhaus 93\";")
        self.BasketballMode.setObjectName("BasketballMode")
        self.BasketballIcon = QtWidgets.QLabel(self.page4)
        self.BasketballIcon.setGeometry(QtCore.QRect(330, 291, 100, 100))
        self.BasketballIcon.setStyleSheet("background-image: url(C:/Users/HP/Desktop/things/offterm/court/basketball/basketball2.png);")
        self.BasketballIcon.setText("")
        self.BasketballIcon.setObjectName("BasketballIcon")
        self.HandIcon = QtWidgets.QLabel(self.page4)
        self.HandIcon.setGeometry(QtCore.QRect(590, 291, 100, 100))
        self.HandIcon.setStyleSheet("background-image: url(C:/Users/HP/Desktop/things/offterm/court/basketball/hand3.png);")
        self.HandIcon.setText("")
        self.HandIcon.setObjectName("HandIcon")
        self.HandMode = QtWidgets.QPushButton(self.page4)
        self.HandMode.setGeometry(QtCore.QRect(800, 260, 220, 171))
        self.HandMode.setStyleSheet("background-color: rgb(255, 184, 2);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Bauhaus 93\";")
        self.HandMode.setObjectName("HandMode")
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.Video5 = QtWidgets.QLabel(self.page5)
        self.Video5.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.Video5.setText("")
        self.Video5.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Video5.setObjectName("Video5")
        self.Points1 = QtWidgets.QLabel(self.page5)
        self.Points1.setGeometry(QtCore.QRect(440, 550, 190, 70))
        self.Points1.setStyleSheet("color: rgb(255,255,255);\n"
"font: 48pt \"Bauhaus 93\";")
        self.Points1.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Points1.setObjectName("Points1")
        self.BasketballIcon1 = QtWidgets.QLabel(self.page5)
        self.BasketballIcon1.setGeometry(QtCore.QRect(412, 241, 200, 200))
        self.BasketballIcon1.setStyleSheet("color: rgb(255,255,255);\n"
"font: 200pt \"Bauhaus 93\";")
        self.BasketballIcon1.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.BasketballIcon1.setObjectName("BasketballIcon1")
        self.Back5 = QtWidgets.QPushButton(self.page5)
        self.Back5.setGeometry(QtCore.QRect(930, 640, 81, 26))
        self.Back5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"font: 15pt \"Bauhaus 93\";")
        self.Back5.setObjectName("Back5")
        self.Time1 = QtWidgets.QLabel(self.page5)
        self.Time1.setGeometry(QtCore.QRect(780, 10, 185, 90))
        self.Time1.setStyleSheet("color: rgb(255,255,255);\n"
"font: 50pt \"Bauhaus 93\";")
        self.Time1.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Time1.setObjectName("Time1")
        self.TimeBackground1 = QtWidgets.QLabel(self.page5)
        self.TimeBackground1.setGeometry(QtCore.QRect(780, 10, 185, 90))
        self.TimeBackground1.setStyleSheet("background-color: rgba(0, 0, 0, 64);")
        self.TimeBackground1.setText("")
        self.TimeBackground1.setObjectName("TimeBackground1")
        self.PointsBackground1 = QtWidgets.QLabel(self.page5)
        self.PointsBackground1.setGeometry(QtCore.QRect(440, 550, 190, 70))
        self.PointsBackground1.setStyleSheet("background-color: rgba(0, 0, 0, 64);")
        self.PointsBackground1.setText("")
        self.PointsBackground1.setObjectName("PointsBackground1")
        self.TimeBackground1.raise_()
        self.PointsBackground1.raise_()
        self.Points1.raise_()
        self.BasketballIcon1.raise_()
        self.Back5.raise_()
        self.Time1.raise_()
        self.stackedWidget.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.Video6 = QtWidgets.QLabel(self.page6)
        self.Video6.setGeometry(QtCore.QRect(0, 0, 1024, 682))
        self.Video6.setText("")
        self.Video6.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Video6.setObjectName("Video6")
        self.HandIcon1 = QtWidgets.QLabel(self.page6)
        self.HandIcon1.setGeometry(QtCore.QRect(412, 241, 200, 200))
        self.HandIcon1.setStyleSheet("color: rgb(255,255,255);\n"
"font: 200pt \"Bauhaus 93\";")
        self.HandIcon1.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.HandIcon1.setObjectName("HandIcon1")
        self.Time2 = QtWidgets.QLabel(self.page6)
        self.Time2.setGeometry(QtCore.QRect(780, 10, 185, 90))
        self.Time2.setStyleSheet("color: rgb(255,255,255);\n"
"font: 50pt \"Bauhaus 93\";")
        self.Time2.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Time2.setObjectName("Time2")
        self.TimeBackground2 = QtWidgets.QLabel(self.page6)
        self.TimeBackground2.setGeometry(QtCore.QRect(780, 10, 185, 90))
        self.TimeBackground2.setStyleSheet("background-color: rgba(0, 0, 0, 64);")
        self.TimeBackground2.setText("")
        self.TimeBackground2.setObjectName("TimeBackground2")
        self.Back6 = QtWidgets.QPushButton(self.page6)
        self.Back6.setGeometry(QtCore.QRect(930, 640, 81, 26))
        self.Back6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"font: 15pt \"Bauhaus 93\";")
        self.Back6.setObjectName("Back6")
        self.Points2 = QtWidgets.QLabel(self.page6)
        self.Points2.setGeometry(QtCore.QRect(440, 550, 190, 70))
        self.Points2.setStyleSheet("color: rgb(255,255,255);\n"
"font: 48pt \"Bauhaus 93\";")
        self.Points2.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)
        self.Points2.setObjectName("Points2")
        self.PointsBackground2 = QtWidgets.QLabel(self.page6)
        self.PointsBackground2.setGeometry(QtCore.QRect(440, 550, 190, 70))
        self.PointsBackground2.setStyleSheet("background-color: rgba(0, 0, 0, 64);")
        self.PointsBackground2.setText("")
        self.PointsBackground2.setObjectName("PointsBackground2")
        self.PointsBackground2.raise_()
        self.TimeBackground2.raise_()
        self.HandIcon1.raise_()
        self.Time2.raise_()
        self.Back6.raise_()
        self.Points2.raise_()
        self.stackedWidget.addWidget(self.page6)

        self.retranslateUi(Basketball)
        self.stackedWidget.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(Basketball)

    def retranslateUi(self, Basketball):
        _translate = QtCore.QCoreApplication.translate
        Basketball.setWindowTitle(_translate("Basketball", "Form"))
        self.ProjectName.setText("Right Now!")
        self.AnalyseMode.setText(_translate("Basketball", "Analyse"))
        self.TrainMode.setText(_translate("Basketball", "Train"))
        self.Back1.setText(_translate("Basketball", "File"))
        self.Total1.setText(_translate("Basketball", "Total:"))
        self.Hit2.setText(_translate("Basketball", "0"))
        self.Back2.setText(_translate("Basketball", "Back"))
        self.Hit1.setText(_translate("Basketball", "Hit:"))
        self.Rate1.setText(_translate("Basketball", "Hit Rate:"))
        self.Speed1.setText(_translate("Basketball", "Speed:"))
        self.Angle1.setText(_translate("Basketball", "Angle:"))
        self.Total2.setText(_translate("Basketball", "0"))
        self.Rate2.setText(_translate("Basketball", "0"))
        self.Speed2.setText(_translate("Basketball", "0"))
        self.Angle2.setText(_translate("Basketball", "0"))
        self.Back5.setText(_translate("Basketball", "Back"))
        self.Time1.setText(_translate("Basketball", "01:00"))
        self.Time2.setText(_translate("Basketball", "01:00"))
        self.Back6.setText(_translate("Basketball", "Back"))
        self.BasketballMode.setText("Basketball\nMode")
        self.HandMode.setText("Hand\nMode")
        self.Stop.setText("Stop")